# Generated by Django 6.1 on 2026-08-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(help_text='Shown on product cards / listing page', max_length=250)),
                ('description', models.TextField(help_text='Full description shown on product detail page')),
                ('ingredients', models.TextField(blank=True)),
                ('nutritional_info', models.TextField(blank=True, help_text='e.g. Energy, Protein, Carbs per 100g')),
                ('image', models.ImageField(upload_to='products/main/')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('weight_value', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('weight_unit', models.CharField(choices=[('kg', 'Kg'), ('g', 'Grams')], default='kg', max_length=2)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (Rs)', max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Actual selling price (Rs)', max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the website without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['category__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
